### PR TITLE
Dockerizing the engine

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Began trying to set up a Docker image for lovelace-image but hit two issues:
1. We'll be trying to run LXC inside Docker which might be tricky to figure out. Docker is set up as a "single service single container" thing and LXC just needs too many services and features I think. I could install `lxc` but couldn't get `lxd` to work on the python:buster (Debian) and python:alpine images.
2. Gotta copy/clone in lovelace-solutions which is a private repository.

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
I'm pretty new to Docker but seems to make sense to have an `engine` container that runs the lovelace-engine and a `code_runner` that provides a secure environment for executing user-submmited code (this will replace the LXC containers).

@benallan Do you have any experience getting multiple Docker containers to talk to each other? From googling it sounds like docker compose is useful but not too sure how to go about doing this.

**Comment by benallan** [comment]
Yeah exactly docker compose will make it easier to have multiple containers that talk to each other. I’m thinking of one container for the website, a second container for the engine, and then the actual user-submitted code will be created in another container (“code-runner”), spun-up just for that run and then deleted right after. 

The only slightly difficult part is how to spin up the temporary containers for the code-runners, since this means that the engine container will have to create another container (and we’re into a containers within containers inception-style hassle...). From what I checked, running a container inside another is more problematic, so it might be better to run the code-runner on the host at the top level, so the website, engine and a number of code-runners all run on the host docker and there are no more containers within containers. To get that to work, we need to give the engine container a bit more access to the host so it has permission to create new containers. 

I think it’ll work fine that way, but the last part has some security implications that I didn’t have time to check yet. Let me see if I can get a demo running this week so we can see how it might work.

**Comment by ali-ramadhan** [comment]
Ah awesome! Yeah sounds like the way to go is to just have containers for each task. I probably shouldn't have spent so much time trying to get LXC to work in Docker lol.

Also, I think you were asking why I went with `archlinux` for the base image. Not sure if this is a good reason but since it's a rolling release distro I can easily install the latest versions of Python, Julia, node.js, etc. but maybe this is easy with something like Debian unstable if they have a Docker image.

**Comment by ali-ramadhan** [comment]
This PR focuses on just dockerizing the engine now. The code runner is being dockerized in PR #64.

**Pull request merged**
